
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ASSIGN COMMA END IDENTIFIER INT LBRACE LPAREN MINUS NUMBER PLUS PRINTF PROGRAMA RBRACE READ RPAREN SEMI STRINGprogram : PROGRAMA IDENTIFIER LPAREN RPAREN LBRACE declarations statements END SEMI RBRACEdeclarations : declaration declarations\n| declarationdeclaration : INT identifier_list SEMIidentifier_list : IDENTIFIER\n| IDENTIFIER COMMA identifier_liststatements : statement\n| statement statementsstatement : READ IDENTIFIER SEMIstatement : IDENTIFIER ASSIGN expression SEMIstatement : PRINTF LPAREN STRING RPARENexpression : IDENTIFIER PLUS IDENTIFIERexpression : NUMBERexpression : IDENTIFIER'
    
_lr_action_items = {'PROGRAMA':([0,],[2,]),'$end':([1,34,],[0,-1,]),'IDENTIFIER':([2,7,8,9,12,13,15,18,23,24,29,32,33,35,],[3,10,-3,17,10,21,-2,25,-4,17,-9,36,-10,-11,]),'LPAREN':([3,14,],[4,22,]),'RPAREN':([4,30,],[5,35,]),'LBRACE':([5,],[6,]),'INT':([6,8,23,],[9,9,-4,]),'READ':([7,8,12,15,23,29,33,35,],[13,-3,13,-2,-4,-9,-10,-11,]),'PRINTF':([7,8,12,15,23,29,33,35,],[14,-3,14,-2,-4,-9,-10,-11,]),'ASSIGN':([10,],[18,]),'END':([11,12,20,29,33,35,],[19,-7,-8,-9,-10,-11,]),'SEMI':([16,17,19,21,25,26,27,31,36,],[23,-5,28,29,-14,33,-13,-6,-12,]),'COMMA':([17,],[24,]),'NUMBER':([18,],[27,]),'STRING':([22,],[30,]),'PLUS':([25,],[32,]),'RBRACE':([28,],[34,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'declarations':([6,8,],[7,15,]),'declaration':([6,8,],[8,8,]),'statements':([7,12,],[11,20,]),'statement':([7,12,],[12,12,]),'identifier_list':([9,24,],[16,31,]),'expression':([18,],[26,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> PROGRAMA IDENTIFIER LPAREN RPAREN LBRACE declarations statements END SEMI RBRACE','program',10,'p_program','parser.py',9),
  ('declarations -> declaration declarations','declarations',2,'p_declarations','parser.py',16),
  ('declarations -> declaration','declarations',1,'p_declarations','parser.py',17),
  ('declaration -> INT identifier_list SEMI','declaration',3,'p_declaration','parser.py',21),
  ('identifier_list -> IDENTIFIER','identifier_list',1,'p_identifier_list','parser.py',25),
  ('identifier_list -> IDENTIFIER COMMA identifier_list','identifier_list',3,'p_identifier_list','parser.py',26),
  ('statements -> statement','statements',1,'p_statements','parser.py',33),
  ('statements -> statement statements','statements',2,'p_statements','parser.py',34),
  ('statement -> READ IDENTIFIER SEMI','statement',3,'p_statement_read','parser.py',38),
  ('statement -> IDENTIFIER ASSIGN expression SEMI','statement',4,'p_statement_assignment','parser.py',42),
  ('statement -> PRINTF LPAREN STRING RPAREN','statement',4,'p_statement_printf','parser.py',46),
  ('expression -> IDENTIFIER PLUS IDENTIFIER','expression',3,'p_expression_plus','parser.py',53),
  ('expression -> NUMBER','expression',1,'p_expression_number','parser.py',57),
  ('expression -> IDENTIFIER','expression',1,'p_expression_identifier','parser.py',61),
]
