
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ASSIGN COMMA DOT FOR IDENTIFIER IF LBRACE LPAREN MINUS NUMBER PLUS RBRACE RELOP RPAREN SEMI STRING WHILEprogram : control_structure_listcontrol_structure_list : control_structure\n| control_structure control_structure_listcontrol_structure : for_loop\n| while_loop\n| if_statementfor_loop : FOR LPAREN assignment SEMI condition SEMI increment RPAREN blockassignment : IDENTIFIER ASSIGN NUMBERcondition : IDENTIFIER RELOP NUMBERincrement : IDENTIFIER PLUSwhile_loop : WHILE LPAREN condition RPAREN blockif_statement : IF LPAREN condition RPAREN blockblock : LBRACE statement_list RBRACEstatement_list : statement\n| statement statement_liststatement : IDENTIFIER DOT IDENTIFIER LPAREN STRING COMMA IDENTIFIER RPAREN SEMI'
    
_lr_action_items = {'FOR':([0,3,4,5,6,26,29,36,42,],[7,7,-4,-5,-6,-11,-12,-13,-7,]),'WHILE':([0,3,4,5,6,26,29,36,42,],[8,8,-4,-5,-6,-11,-12,-13,-7,]),'IF':([0,3,4,5,6,26,29,36,42,],[9,9,-4,-5,-6,-11,-12,-13,-7,]),'$end':([1,2,3,4,5,6,10,26,29,36,42,],[0,-1,-2,-4,-5,-6,-3,-11,-12,-13,-7,]),'LPAREN':([7,8,9,41,],[11,12,13,43,]),'IDENTIFIER':([11,12,13,19,27,30,32,38,45,48,],[15,17,17,17,33,35,33,41,46,-16,]),'SEMI':([14,24,25,28,47,],[19,30,-8,-9,48,]),'ASSIGN':([15,],[20,]),'RPAREN':([16,18,28,34,40,46,],[21,23,-9,39,-10,47,]),'RELOP':([17,],[22,]),'NUMBER':([20,22,],[25,28,]),'LBRACE':([21,23,39,],[27,27,27,]),'RBRACE':([31,32,37,48,],[36,-14,-15,-16,]),'DOT':([33,],[38,]),'PLUS':([35,],[40,]),'STRING':([43,],[44,]),'COMMA':([44,],[45,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'control_structure_list':([0,3,],[2,10,]),'control_structure':([0,3,],[3,3,]),'for_loop':([0,3,],[4,4,]),'while_loop':([0,3,],[5,5,]),'if_statement':([0,3,],[6,6,]),'assignment':([11,],[14,]),'condition':([12,13,19,],[16,18,24,]),'block':([21,23,39,],[26,29,42,]),'statement_list':([27,32,],[31,37,]),'statement':([27,32,],[32,32,]),'increment':([30,],[34,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> control_structure_list','program',1,'p_program','parser.py',6),
  ('control_structure_list -> control_structure','control_structure_list',1,'p_control_structure_list','parser.py',10),
  ('control_structure_list -> control_structure control_structure_list','control_structure_list',2,'p_control_structure_list','parser.py',11),
  ('control_structure -> for_loop','control_structure',1,'p_control_structure','parser.py',16),
  ('control_structure -> while_loop','control_structure',1,'p_control_structure','parser.py',17),
  ('control_structure -> if_statement','control_structure',1,'p_control_structure','parser.py',18),
  ('for_loop -> FOR LPAREN assignment SEMI condition SEMI increment RPAREN block','for_loop',9,'p_for_loop','parser.py',25),
  ('assignment -> IDENTIFIER ASSIGN NUMBER','assignment',3,'p_assignment','parser.py',29),
  ('condition -> IDENTIFIER RELOP NUMBER','condition',3,'p_condition','parser.py',33),
  ('increment -> IDENTIFIER PLUS','increment',2,'p_increment','parser.py',37),
  ('while_loop -> WHILE LPAREN condition RPAREN block','while_loop',5,'p_while_loop','parser.py',44),
  ('if_statement -> IF LPAREN condition RPAREN block','if_statement',5,'p_if_statement','parser.py',51),
  ('block -> LBRACE statement_list RBRACE','block',3,'p_block','parser.py',58),
  ('statement_list -> statement','statement_list',1,'p_statement_list','parser.py',62),
  ('statement_list -> statement statement_list','statement_list',2,'p_statement_list','parser.py',63),
  ('statement -> IDENTIFIER DOT IDENTIFIER LPAREN STRING COMMA IDENTIFIER RPAREN SEMI','statement',9,'p_statement','parser.py',67),
]
